### ISSUE TITLE
xslt transform misses column changes

### ISSUE THREAD

**Issue by saracarl** [CivilWarGovernorsOfKentucky/Mashbill#31]

**Comment by PatrickALewis** [comment]
Whitney suggested recoding these without the columns, which doesn't correct the xslt issue but will still allow us to continue annotation work. The words being more important than the format.

**Comment by PatrickALewis** [comment]
Also, looks like <pb> resets the issue. Exploring other tags that insert a similar division break that don't have the semantic baggage as <pb>. Much like how Jeff swapped <ab> for <p> in some cases. 

If so, we can insert these tags after problematic columns and get them rendering again.

**Comment by benwbrum** [comment]
There's a chance this may have had side effects on #87, and the Mashbill TEI code needs to be updated to reflect this.

**Comment by jiaola** [comment]
From @JeffDycus 

>  The problem we are trying to remedy can be seen on this document: http://discovery.civilwargovernors.org/document/KYR-0362-001-0001.  If you compare the transcript to the image you can see that where the text changes from two columns to a single column after M. P. Marshall the content of the single column is lost.  If you click the download link and download the TEI you will see that that content is in the TEI and that the TEI is valid, but the stylesheet fails to display this information.  This missing content is hindering the annotation work on the documents where there are changing numbers of columns.  Here are a couple of other documents to illustrate the problem:
http://discovery.civilwargovernors.org/document/KYR-0001-004-1357
http://discovery.civilwargovernors.org/document/KYR-0001-004-0002
http://discovery.civilwargovernors.org/document/KYR-0001-004-1338

**Comment by jiaola** [comment]
@JeffDycus Here's a fixed example. Please let me know if it looks right or not. 
<img width="1145" alt="screen shot 2017-09-18 at 11 31 18 pm" src="https://user-images.githubusercontent.com/9097689/30574685-a8284a22-9cc9-11e7-8fc7-d99caa813d50.png">

**Comment by jiaola** [comment]
@JeffDycus Also please send me a few examples with more than two columns.

**Comment by whitneysmith** [comment]
That looks good to me!
Here are a few more examples with more than two columns:
KYR-0001-023-0092
KYR-0001-019-0109
KYR-0001-007-0266
KYR-0001-007-0374
KYR-0001-007-0540
KYR-0001-017-0162
KYR-0001-017-0246

**Comment by jiaola** [comment]
A 4-column and a 5-column display. 

<img width="1920" alt="screen shot 2017-09-19 at 10 31 17 am" src="https://user-images.githubusercontent.com/9097689/30624534-025c60d8-9d8c-11e7-93b4-5dc2d1b340ae.png">
<img width="1675" alt="screen shot 2017-09-19 at 10 06 56 am" src="https://user-images.githubusercontent.com/9097689/30624535-025e4e16-9d8c-11e7-866d-723865140b78.png">

**Comment by JeffDycus** [comment]
Hi Dazhi,

I uploaded the css and xslt files you modified to our test site, but I can see that the display for documents on that site has improved, see http://test.discovery.civilwargovernors.org/document/KYR-0001-007-0266.  Do you have any ideas here?

-Jeff

**Comment by jiaola** [comment]
@JeffDycus There was another commit that I didn't link to this ticket: 
https://github.com/CivilWarGovernorsOfKentucky/Omeka/commit/da113bf1b816a9f33fdd63af934e4c3db4a0324d

It updates the php file so that the hostname of the current server is used, instead of the hard coded production server hostname.

**Comment by JeffDycus** [comment]
Hi Dazhi,

First, I want to apologize.  I re-read the comment I left before and I realize I made a pretty bad typo.  Where I said I can see improvement I meant to say I can not see improvement. I'm very sorry for the mistake. I think the changes to the css file has caused major changes to the test site:
![2017-09-21 10_05_59-Alexander Ostrander to Thomas E. Bramlette · Civil War Governors of Kentucky_ Ea.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/587e8229b0aa9a1500c907cc/125516c66e82c728ace21e0d46bac4cb74cfd3f0c2bbee03f50dcfc47c79722a6425af2e6884ed2cba503b2e1c1b0cfd1f0c0a06ecbdd63bc2ee632ddb1f1b98cf7d2d3697604df9fcc64aaff33d30f816c3efe09a2b91aa2d52b8cdda0d6041475b99a00b25dbcc158c1da510a82245d142247ff43674231dc14d313e617523aca9d650d2d069a4e9117b50cbe0e6fa1643a52add935a637f4719fb7466ea5f03c335da54724feabccefc124c0e1e01cfe3c5d3bde7d22338.jpg)

I haven't looked closely at the modifications to the style.css file.
 I appreciate the fix for the DropboxTEI plugin, but I haven't implemented that change yet.

**Comment by JeffDycus** [comment]
I apologize again, I had uploaded the wrong style.css file.  The style is back on the site.

**Comment by jiaola** [comment]
@JeffDycus Have you updated the php file I mentioned earlier? 

[CivilWarGovernorsOfKentucky/Omeka@da113bf](https://github.com/CivilWarGovernorsOfKentucky/Omeka/commit/da113bf1b816a9f33fdd63af934e4c3db4a0324d)

**Comment by JeffDycus** [comment]
Whitney and I have been comparing some document between the test site (http://test.discovery.civilwargovernors.org/document/KYR-0001-017-0246) where the new xsl and css files have been installed and the live site (http://discovery.civilwargovernors.org/document/KYR-0001-017-0246) still using the old css and xsl and here is what we've found so far:

On the document linked above the columns render correctly on the test site but not the live site.  
KYR-0001-007-0266 No change on test site.  This is the other one that looked good in the screenshot.
KYR-0001-004-1357 No change on test site. Single column on last page still does not appear.
KYR-0001-004-0002 No change on test site. Single column at top of second page does not appear, though the following paragraph does show up.
KYR-0001-004-1338 No change on test site. Signatures in two columns at bottom of page three do not appear.

**Comment by jiaola** [comment]
@JeffDycus http://test.discovery.civilwargovernors.org/document/KYR-0001-007-0266 shows the changes on the test site for me. 

Maybe those pages were cached? Try refresh the page a few times?

**Comment by PatrickALewis** [comment]
I'm seeing those changes to that document now.

**Comment by JeffDycus** [comment]
I updated that php file about a half an hour ago, so that probably made the difference.  Sorry for the false start, but so far this looks good to me.  I think the next step is to test these documents in mashbill to see if the changes a negative effect there.  Maybe @benwbrum and @saracarl  can devise a way to test this?  Maybe someone on the editorial staff can go through the list of documents  with display problems to see how they are rendering on the test site?

**Comment by JeffDycus** [comment]
I've applied these changes to the live Omeka site:

https://github.com/CivilWarGovernorsOfKentucky/Omeka/commit/da113bf1b816a9f33fdd63af934e4c3db4a0324d
https://github.com/CivilWarGovernorsOfKentucky/Omeka/commit/5c12925f4cf013ecfabab3ae811cd3dc5a67114d
