### ISSUE TITLE
Link Documents to Bios with XML

### ISSUE THREAD

**Issue by saracarl** [CivilWarGovernorsOfKentucky/Mashbill#61]
We need to use resolution rules within our XML that allow navigation from `xml:id` attributes in documents to the corresponding entity bio.

**Comment by benwbrum** [comment]
From an earlier discussion via email:

Although many TEI projects stick all of their personography/placeography information in a single file and reference it from elsewhere, I feel like that would be unwieldy for this number of documents and wouldn't give a good picture of the researcher's work, since respStmt elements would mix up different people's research on different biographies.

I think the best approach for us is a variation on the one adopted by the Map of Early Modern London in their connection between documents and entries for people/places: https://mapoflondon.uvic.ca/

The TEI behind documents like the Will of Eliza Whitley uses the kinds of IDs in references you describe:

<l>By <ref target="mol:THAM2">Thames</ref> you ſhal haue <name type="org" ref="mol:BREW2">Brewers</name> ſtore,</l>

That ID, "BREW2" refers off to a separate document with an "orgography" of the Worshipful Company of Brewers
https://mapoflondon.uvic.ca/BREW2.htm (Interestingly, if you look at the XML behind the orgography, it turns out to be a list of all organizations which is soft-linked for each component organization.) 

We'd want to do the same thing, with separate files for each entity.  (I'd also prefer orgName or personName over their use of name with a type attribute.)

The "mol" prefix is a project-specific prefix that gives instructions on how to navigate the TEI.  We'd want to come up with our own (likely "cwgk"), and use the results to point to the entity files the annotation tool produces.

**Comment by saracarl** [comment]
1)  toRef in the entity and document file xml production code -- add a cwgk

2)  Add to the TEI document header section:
  <encodingDesc>
    <listPrefixDef xmlns:xi="http://www.w3.org/2001/XInclude" xml:id="inc_global_prefixDef">
        <prefixDef ident="cwgk" matchPattern="(.+)" replacementPattern="../biography_xml/$1.xml">
        </prefixDef>
      </listPrefixDef>
   </encodingDesc>

I don't know how to test this --  how does this resolve -- do the filenames need to be like "cwgkN0001.xml" or just N0001.xml?  That needs more research.

**Comment by saracarl** [comment]
`<prefixDef ident="ref"
 matchPattern="([a-z]+)"
 replacementPattern="../../references/references.xml#$1">
 <p> In the context of this project, private URIs with
   the prefix "ref" point to <gi>div</gi> elements in
   the project's global references.xml file.
 </p>
</prefixDef>
`
