### ISSUE TITLE
How to encode race & gender in TEI

### ISSUE THREAD

**Issue by saracarl** [CivilWarGovernorsOfKentucky/Mashbill#66]

**Comment by saracarl** [comment]
from @PatrickALewis 

 

<trait type=”race” subtype=”white”/> with the vocabulary of subtypes drawn from the Mashbill list. Looks like we can stack up a number of these tags if people are described in multiple ways.

 

We considered the <sex> tag for gender, but since we’re not precisely tagging sex but rather gender, it follows that we use the same formula.

<trait type=”gender” subtype=”F”/> or M or U.

 

Both can go in the <particDesc> / <person> section of the header somewhere in with name, birth, and death

**Comment by benwbrum** [comment]
Original email:
The Theory: http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ND.html#NDPERSbp

`<trait type=”race” subtype=”white”/>` with the vocabulary of subtypes drawn from the Mashbill list. Looks like we can stack up a number of these tags if people are described in multiple ways.

 

We considered the `<sex>` tag for gender, but since we’re not precisely tagging sex but rather gender, it follows that we use the same formula.

`<trait type=”gender” subtype=”F”/>` or `M` or `U`.

 

Both can go in the `<particDesc>` / `<person>` section of the header somewhere in with name, birth, and death
